defaults: &defaults
  login: ankur.malhotra7_api5.ymail.com
  password: C9DT4KTNRZE5BMET
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A2bqOXH-tATGOTcN3F3eHYGutufY
 

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults